# -*- coding: utf-8 -*-
"""data analysis - pie charts - education vs. income.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MheVoTnyOIbT3BQrNChBEEYKWqHX6I7S
"""

import pandas as pd
import matplotlib.pyplot as plt

data1000 = pd.read_csv('/content/Adult-1000_decission_class_mapped.csv')

for el in range(len(data1000['education'])):
    if (data1000.at[el,'education-num']) <=9:
        data1000.at[el,'education'] = "0" + str(data1000.at[el,'education-num']) + " " + data1000.at[el,'education']
    else:
        data1000.at[el,'education'] = str(data1000.at[el,'education-num']) + " " + data1000.at[el,'education']

class1 = {}
for el in data1000[data1000['decision_class'] == ' >50K']['education']:
    if el in class1:
        class1[el] += 1
    else:
        class1[el] =1


class0 = {}
for el in data1000[data1000['decision_class'] == ' <=50K']['education']:
    if el in class0:
        class0[el] += 1
    else:
        class0[el] =1


# stworzenie DataFrame dla klasy >50K
df1 = pd.DataFrame({' >50K': class1})

# stworzenie DataFrame dla klasy <=50K
df0 = pd.DataFrame({' <=50K': class0})

labels = df1[' >50K'].index.tolist()

chart = df1[' >50K'].plot.pie(labels=labels, autopct='%1.1f%%', pctdistance=0.8, labeldistance=1.05, startangle=185, counterclock=False, textprops={'fontsize': 7}, title='>50K')
chart.set_ylabel('')
chart.legend(loc='center left', bbox_to_anchor=(1.2, 0.5))

plt.show()
print(f"{df1}\n{'Sum:'}{df1[' >50K'].sum()}")


labels = df0[' <=50K'].index.tolist()

chart = df0[' <=50K'].plot.pie(labels=labels, autopct='%1.1f%%', pctdistance=0.8, labeldistance=1.05, startangle=200, counterclock=False, textprops={'fontsize': 7}, title='<=50K')
chart.set_ylabel('')
chart.legend(loc='center left', bbox_to_anchor=(1.2, 0.5))

plt.show()
print(f"{df0}\n{'Sum:'}{df0[' <=50K'].sum()}")